### ISSUE TITLE
Long forms are no longer scrollable and the fields gets cut off

### ISSUE THREAD

**Issue by evagm** [aws-amplify/amplify-ui#1665]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

Packages versions:
```
"@aws-amplify/ui": "^3.5.1",
"@aws-amplify/ui-react": "^2.14.1",
```

Part of the form is no longer visible / accessible when the form in the create account tab has a larger height than the height of the  browser. 

### What's the expected behaviour?

A user should be able to scroll down the form to fill it out and access the create account button when the form is taller than the browser height.

### Help us reproduce the bug!

Add multiple fields to your form so that the form is larger than the height of the browser.

### Additional information and screenshots

styles that were available in versions:
```
"@aws-amplify/ui": "^3.0.5",
"@aws-amplify/ui-react": "^2.1.5",
```

By re-introducing these styles, my issue is resolved. 

```css
[data-amplify-authenticator][data-variation=modal] [data-amplify-router-content] {
    max-height: 60vh;
    overflow-y: auto;
    background: linear-gradient(#fff 30%,hsla(0,0%,100%,0)) top,linear-gradient(hsla(0,0%,100%,0),#fff 70%) bottom,radial-gradient(farthest-side at 50% 0,rgba(0,0,0,.15),transparent) top,radial-gradient(farthest-side at 50% 100%,rgba(0,0,0,.15),transparent) bottom;
    background-repeat: no-repeat;
    background-size: 100% 40px,100% 40px,100% 14px,100% 14px;
    background-attachment: local,local,scroll,scroll;
}
```

example (duplicated fields to showcase issue):
<img width="682" alt="Screen Shot 2022-04-11 at 2 26 39 PM" src="https://user-images.githubusercontent.com/14237452/162805858-aacb2fa3-548c-4c1a-9dd3-8aa49c9df99d.png">
